# Generated by Django 2.2.3 on 2019-07-10 12:58

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volcano',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unsur', models.CharField(max_length=100)),
                ('keterangan', models.CharField(max_length=254)),
                ('thn_terbit', models.IntegerField()),
                ('wilayah', models.CharField(max_length=100)),
                ('tipe_gnapi', models.CharField(max_length=50)),
                ('kode_gnapi', models.CharField(max_length=50)),
                ('rotate', models.IntegerField()),
                ('depmag', models.IntegerField()),
                ('eru', models.IntegerField()),
                ('lav', models.IntegerField()),
                ('matga', models.IntegerField()),
                ('mon', models.IntegerField()),
                ('tek', models.IntegerField()),
                ('vei', models.IntegerField()),
                ('lcode', models.CharField(max_length=50)),
                ('fcode', models.CharField(max_length=50)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
    ]
