# Generated by Django 2.2.3 on 2019-07-11 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0004_auto_20190711_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='shape',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='world.Shape'),
            preserve_default=False,
        ),
    ]
