# Generated by Django 2.2.3 on 2019-07-11 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0005_layer_shape'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shape',
            name='name',
            field=models.CharField(max_length=512),
        ),
    ]
